name: CI
on:
  push:
    branches:
      - master
    tags: '**'
  pull_request:
    branches:
      - master

jobs:

  main:
    name: main
    runs-on: ubuntu-latest
    steps:
      - name: Main
        shell: bash
        env:
          DOCKER_IMAGE_NAME: "rchain/rnode"
        run: |
          if [[ $GITHUB_EVENT_NAME == "push" ]]; then
            echo PUSH
            suffix=${GITHUB_REF#refs/*/}
          elif [[ $GITHUB_EVENT_NAME == "pull_request" ]]
            echo PULL_REQUEST
            suffix=${GITHUB_REF#refs/pull//*}
          fi

          image_name=$DOCKER_IMAGE_NAME-$suffix

          if [[ $suffix == "master" ]]; then
            echo ON MASTER!!!
          fi

          echo SUFFIX $suffix

          echo IMAGE $image_name

          echo GITHUB_EVENT_NAME $GITHUB_EVENT_NAME

          echo HEAD $GITHUB_HEAD_REF

          echo BASE $GITHUB_BASE_REF

          echo RUN_ID $GITHUB_RUN_ID

  release_docker_image:
    name: Release Docker Image
    needs:
      - main
    if: "github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master')"
    runs-on: ubuntu-latest
    steps:
      - name: Publish Docker Image
        shell: bash
        run: |
          echo Docker release !!

  bors_success:
    name: bors build finished
    needs:
      - release_docker_image
    if: "github.event_name == 'push' && (github.ref == 'refs/heads/master') && success()"
    runs-on: ubuntu-latest
    steps:
      - name: BORS execute
        shell: bash
        run: |
          echo BORS FINISHED !!!!
