name: CI
on:
  push:
    branches:
      - master
    tags: '**'
  pull_request:
    branches:
      - dev
      - 'feature/**'

jobs:

  main:
    name: main
    runs-on: ubuntu-latest
    steps:
      - name: Main
        shell: bash
        run: |
          echo MAIN

  release_docker_image:
    name: Release Docker Image
    needs:
      - main
    if: "github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master')"
    runs-on: ubuntu-latest
    steps:
      - name: Publish Docker Image
        shell: bash
        run: |
          image_name=$DOCKER_IMAGE_NAME

          if [[ $GITHUB_REF == refs/heads/* ]]; then
              image_name+=-$GITHUB_REF
          fi

          echo TAG/BRANCH : ${GITHUB_REF#refs/tags/}, ${GITHUB_REF#refs/*/}

  bors_success:
    name: bors build finished
    needs:
      - release_docker_image
    if: "github.event_name == 'push' && (github.ref == 'refs/heads/master') && success()"
    runs-on: ubuntu-latest
    steps:
      - name: BORS execute
        shell: bash
        run: |
          echo BORS FINISHED !!!!
