name: CI
on:
  push:
    branches:
      - master
      - trying
      - staging
    tags: '**'
  pull_request:
    branches:
      - master

jobs:

  base:
    name: Base job
    runs-on: ubuntu-latest
    outputs:
      GIT_BRANCH: ${{ env.GIT_BRANCH }}
      VERSION: ${{ env.VERSION }}
    steps:
      - name: Clone Repository
        uses: actions/checkout@v1
      - name: Set output
        shell: bash
        run: |
          version="`git describe --tags --always`"

          # Find related HEAD branch
          if [[ $GITHUB_REF =~ ^refs/tags/ ]]; then
            raw=$(git branch -r --contains ${{ github.ref }})
            branch=${raw/origin\/}
          elif [[ $GITHUB_REF =~ ^refs/heads/ ]]; then
            branch=${GITHUB_REF#refs/*/}
          else
            branch=$GITHUB_HEAD_REF
          fi

          echo "VERSION=$version" >> $GITHUB_ENV
          echo "GIT_BRANCH=$branch" >> $GITHUB_ENV

          echo VERSION $version
          echo BRANCH $branch

  main:
    name: Main job
    runs-on: ubuntu-latest
    needs:
      - base
    steps:
      - name: Main step
        shell: bash
        env:
          DOCKER_IMAGE_NAME: "rchain/rnode"
          VERSION: ${{ needs.base.outputs.VERSION }}
          GIT_BRANCH: ${{ needs.base.outputs.GIT_BRANCH }}
        run: |
          suffix=""
          ci_run=""

          # CI run number if trying or merging
          if [[ $GIT_BRANCH =~ ^(trying|staging)$ ]]; then
            suffix="-$GIT_BRANCH"

            if [[ $GIT_BRANCH =~ ^trying$ ]]; then
              ci_run="-ci-$GITHUB_RUN_NUMBER"
            fi
          fi

          image_name="$DOCKER_IMAGE_NAME$suffix"
          img_version="$image_name:$VERSION$ci_run"
          img_latest="$image_name:latest"

          # Push Docker image
          #set -x
          echo docker tag coop.rchain/rnode:latest $img_version
          echo docker push $img_version

          # Tag Docker image as latest if dev branch is tagged
          if [[ $GITHUB_REF =~ ^refs/tags/ ]] && [[ $branch =~ ^dev$ ]]; then
            echo docker tag coop.rchain/rnode:latest $img_latest
            echo docker push $img_latest
          fi

          echo ---------------------

          echo IMAGE $image_name
          echo GITHUB_REF $GITHUB_REF
          echo GITHUB_RUN_NUMBER $GITHUB_RUN_NUMBER
          echo GITHUB_EVENT_NAME $GITHUB_EVENT_NAME
          echo HEAD $GITHUB_HEAD_REF
          echo BASE $GITHUB_BASE_REF

  release_docker_image:
    name: Release Docker Image
    needs:
      - base
      - main
    #if: "github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/trying')"
    runs-on: ubuntu-latest
    steps:
      - name: Publish Docker Image
        shell: bash
        env:
          DOCKER_IMAGE_NAME: "rchain/rnode"
        run: |
          echo Docker release !!

          echo main GIT_BRANCH ${{ needs.main.outputs.GIT_BRANCH }}
          echo base GIT_BRANCH ${{ needs.base.outputs.GIT_BRANCH }}
          echo jobs base GIT_BRANCH ${{ jobs.base.outputs.GIT_BRANCH }}

  bors_success:
    name: bors build finished
    needs:
      - release_docker_image
    if: "github.event_name == 'push' && (github.ref == 'refs/heads/trying') && success()"
    runs-on: ubuntu-latest
    steps:
      - name: BORS execute
        shell: bash
        run: |
          echo BORS FINISHED !!!!
