name: CI
on:
  push:
    branches:
      - staging
      - trying
    tags: '**'
  pull_request:
    branches:
      - dev
      - 'feature/**'

jobs:

  release_docker_image:
    name: Release Docker Image
    needs:
      - run_unit_tests
    if: "github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master')"
    runs-on: ubuntu-latest
    steps:
      - name: Publish Docker Image
        shell: bash
        run: |
          echo Publish docker !!!!

  bors_success:
    name: bors build finished
    needs:
      - release_docker_image
    if: "github.event_name == 'push' && (github.ref == 'refs/heads/master') && success()"
    runs-on: ubuntu-latest
    steps:
      - name: BORS execute
        shell: bash
        run: |
          echo BORS FINISHED !!!!
