name: CI
on:
  push:
    branches:
      - master
      - trying
    tags: '**'
  pull_request:
    branches:
      - master

jobs:

  main:
    name: main
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v1
      - name: Main
        shell: bash
        env:
          DOCKER_IMAGE_NAME: "rchain/rnode"
        run: |
          git_ref=${GITHUB_REF#refs/*/}
          version="`git describe --tags --always`"
          suffix=""
          ci_run=""

          # CI run number if trying or merging
          if [[ $git_ref =~ ^(trying|staging)$ ]]; then
            suffix="-$git_ref"

            if [[ $git_ref =~ ^trying$ ]]; then
              ci_run="-ci-$GITHUB_RUN_NUMBER"
            fi
          fi

          image_name="$DOCKER_IMAGE_NAME$suffix"
          img_version="$image_name:$version$ci_run"
          img_latest="$image_name:latest"

          # Push Docker image
          #set -x
          echo docker tag coop.rchain/rnode:latest $img_version
          echo docker push $img_version

          # Tag Docker image as latest if dev branch is tagged
          if [[ $GITHUB_REF =~ ^refs/tags/ ]]; then
            echo docker tag coop.rchain/rnode:latest $img_latest
            echo docker push $img_latest
          fi

          echo ---------------------

          echo IMAGE $image_name
          echo GITHUB_REF $GITHUB_REF
          echo GITHUB_RUN_NUMBER $GITHUB_RUN_NUMBER
          echo GITHUB_EVENT_NAME $GITHUB_EVENT_NAME
          echo HEAD $GITHUB_HEAD_REF
          echo BASE $GITHUB_BASE_REF

  release_docker_image:
    name: Release Docker Image
    needs:
      - main
    if: "github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/trying')"
    runs-on: ubuntu-latest
    steps:
      - name: Publish Docker Image
        shell: bash
        env:
          DOCKER_IMAGE_NAME: "rchain/rnode"
        run: |
          echo Docker release !!

  bors_success:
    name: bors build finished
    needs:
      - release_docker_image
    if: "github.event_name == 'push' && (github.ref == 'refs/heads/trying') && success()"
    runs-on: ubuntu-latest
    steps:
      - name: BORS execute
        shell: bash
        run: |
          echo BORS FINISHED !!!!
